name: build

on:
  push:
    branches:
    - '*'

jobs:
  build:
    name: Lint & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 🛎️
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up Python 🔧
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: 3.14
      - name: Install dependencies ⚙️
        run: pip install bandit pylint pytest -r requirements.txt
      - name: Linter 🔎
        run: pylint sir_app.py
      - name: Tests ☑
        run: pytest
      - name: Looking for security vulnerabilities 🔎
        run: bandit sir_app.py
